# Generated by Django 5.2 on 2025-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='approved',
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
